
CREATE SEQUENCE SEQ_PAIS START WITH 1;

CREATE TABLE TB_PAIS(

    ID_PAIS NUMBER NOT NULL,
    NOME_PAIS VARCHAR2(255) NOT NULL,
    CODIGO_SISCOMEX NUMBER NOT NULL,
    CONSTRAINT TB_PAIS_ID_PK PRIMARY KEY(ID_PAIS),
    CONSTRAINT TB_PAIS_NOME_UN UNIQUE(NOME_PAIS),
    CONSTRAINT TB_PAIS_CODIGO_SISCOMEX_UN UNIQUE(CODIGO_SISCOMEX)

);

CREATE SEQUENCE SEQ_UNIDADE_FEDERATIVA START WITH 1;

CREATE TABLE TB_UNIDADE_FEDERATIVA(

    ID_UNIDADE_FEDERATIVA NUMBER NOT NULL,
    NOME_UNIDADE_FEDERATIVA VARCHAR2(255) NOT NULL,
    SIGLA_UNIDADE_FEDERATIVA CHAR(2) NOT NULL,
    CODIGO_IBGE NUMBER NOT NULL,
    ID_PAIS NUMBER NOT NULL,
    CONSTRAINT TB_UNIDADE_FEDERATIVA_ID_PK PRIMARY KEY(ID_UNIDADE_FEDERATIVA),
    CONSTRAINT TB_UNIDADE_FEDERATIVA_NOME_UN UNIQUE(NOME_UNIDADE_FEDERATIVA),
    CONSTRAINT TB_UNIDADE_FEDERATIVA_SIGLA_UN UNIQUE(SIGLA_UNIDADE_FEDERATIVA),
    CONSTRAINT TB_UNIDADE_FEDERATIVA_CODIGO_IBGE_UN UNIQUE(CODIGO_IBGE),
    CONSTRAINT TB_UNIDADE_FEDERATIVA_ID_PAIS_FK FOREIGN KEY(ID_PAIS) REFERENCES TB_PAIS(ID_PAIS)

);

CREATE SEQUENCE SEQ_CIDADE START WITH 1;

CREATE TABLE TB_CIDADE(

    ID_CIDADE NUMBER NOT NULL,
    NOME_CIDADE VARCHAR2(255) NOT NULL,
    ID_UNIDADE_FEDERATIVA NUMBER NOT NULL,
    CONSTRAINT TB_CIDADE_ID_PK PRIMARY KEY(ID_CIDADE),
    CONSTRAINT TB_CIDADE_ID_UNIDADE_FEDERATIVA_FK FOREIGN KEY(ID_UNIDADE_FEDERATIVA) REFERENCES TB_UNIDADE_FEDERATIVA(ID_UNIDADE_FEDERATIVA)

);


CREATE SEQUENCE SEQ_PESSOA START WITH 1;



CREATE TABLE TB_PESSOA(

    ID_PESSOA NUMBER NOT NULL,
    NOME_PESSOA VARCHAR2(255) NOT NULL,
    CPF VARCHAR2(15) NOT NULL,
    RG VARCHAR2(15),
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO CHAR(1),
    CONSTRAINT TB_PESSOA_ID_PK PRIMARY KEY(ID_PESSOA),
    CONSTRAINT TB_PESSOA_CPF_UN UNIQUE(CPF)

);

CREATE SEQUENCE SEQ_ENDERECO_PESSOAL START WITH 1;

CREATE TABLE TB_ENDERECO_PESSOAL(

    ID_ENDERECO_PESSOAL NUMBER NOT NULL,
    CEP VARCHAR2(10),
    ENDERECO VARCHAR2(255) NOT NULL,
    NUMERO VARCHAR2(255) NOT NULL,
    BAIRRO VARCHAR2(255) NOT NULL,
    ID_CIDADE NUMBER NOT NULL,
    ID_PESSOA NUMBER NOT NULL,
    CONSTRAINT TB_ENDERECO_PESSOAL_ID_PK PRIMARY KEY(ID_ENDERECO_PESSOAL),
    CONSTRAINT TB_ENDERECO_PESSOAL_ID_CIDADE_FK FOREIGN KEY(ID_CIDADE) REFERENCES TB_CIDADE(ID_CIDADE),
    CONSTRAINT TB_ENDERECO_PESSOAL_ID_PESSOA_FK FOREIGN KEY(ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)

);

CREATE SEQUENCE SEQ_EMPRESA START WITH 1;

CREATE TABLE TB_EMPRESA(

    ID_EMPRESA NUMBER NOT NULL,
    NOME_EMPRESA VARCHAR2(255) NOT NULL,
    CNPJ VARCHAR(15) NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    CONSTRAINT TB_EMPRESA_ID_PK PRIMARY KEY(ID_EMPRESA),
    CONSTRAINT TB_EMPRESA_CNPJ_UN UNIQUE(CNPJ)

);

CREATE SEQUENCE SEQ_ENDERECO_EMPRESARIAL START WITH 1;

CREATE TABLE TB_ENDERECO_EMPRESARIAL(

    ID_ENDERECO_EMPRESARIAL NUMBER NOT NULL,
    CEP VARCHAR2(10),
    ENDERECO VARCHAR2(255) NOT NULL,
    NUMERO VARCHAR2(255) NOT NULL,
    BAIRRO VARCHAR2(255) NOT NULL,
    ID_CIDADE NUMBER NOT NULL,
    ID_EMPRESA NUMBER NOT NULL,
    CONSTRAINT TB_ENDERECO_EMPRESARIAL_ID_PK PRIMARY KEY(ID_ENDERECO_EMPRESARIAL),
    CONSTRAINT TB_ENDERECO_EMPRESARIAL_ID_CIDADE_FK FOREIGN KEY(ID_CIDADE) REFERENCES TB_CIDADE(ID_CIDADE),
    CONSTRAINT TB_ENDERECO_EMPRESARIAL_ID_EMPRESA_FK FOREIGN KEY(ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)

);

CREATE SEQUENCE SEQ_DEPARTAMENTO START WITH 1;

CREATE TABLE TB_DEPARTAMENTO(
    
    ID_DEPARTAMENTO NUMBER NOT NULL,
    NOME_DEPARTAMENTO VARCHAR2(255) NOT NULL,
    ID_EMPRESA NUMBER NOT NULL,
    CONSTRAINT TB_DEPARTAMENTO_ID_PK PRIMARY KEY(ID_DEPARTAMENTO),
    CONSTRAINT TB_DEPARTAMENTO_NOME_UN UNIQUE(NOME_DEPARTAMENTO),
    CONSTRAINT TB_DEPARTAMENTO_ID_EMPRESA_FK FOREIGN KEY(ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)

);

CREATE SEQUENCE SEQ_SETOR START WITH 1;

CREATE TABLE TB_SETOR(

    ID_SETOR NUMBER NOT NULL,
    NOME_SETOR VARCHAR2(255) NOT NULL,
    ID_DEPARTAMENTO NUMBER NOT NULL,
    CONSTRAINT TB_SETOR_ID_PK PRIMARY KEY(ID_SETOR),
    CONSTRAINT TB_SETOR_NOME_UN UNIQUE(NOME_SETOR),
    CONSTRAINT TB_SETOR_ID_DEPARTAMENTO_FK FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES TB_DEPARTAMENTO(ID_DEPARTAMENTO)

);

CREATE SEQUENCE SEQ_CARGO START WITH 1;

CREATE TABLE TB_CARGO(

    ID_CARGO NUMBER NOT NULL,
    NOME_CARGO VARCHAR2(255) NOT NULL,
    SALARIO NUMBER(11,2) NOT NULL,
    CONSTRAINT TB_CARGOID_PK PRIMARY KEY(ID_CARGO)

);

CREATE SEQUENCE SEQ_FUNCIONARIO START WITH 1;

CREATE TABLE TB_FUNCIONARIO(

    ID_FUNCIONARIO NUMBER NOT NULL,
    MATRICULA VARCHAR2(20) NOT NULL,
    DATA_INGRESSO DATE NOT NULL,
    PIS_PASEP VARCHAR2(15) NOT NULL,
    ID_PESSOA NUMBER NOT NULL,
    ID_CARGO NUMBER NOT NULL,
    ID_SETOR NUMBER NOT NULL,
    CONSTRAINT TB_FUNCIONARIO_ID_PK PRIMARY KEY(ID_FUNCIONARIO),
    CONSTRAINT TB_FUNCIONARIO_MATRICULA_UN UNIQUE(MATRICULA),
    CONSTRAINT TB_FUNCIONARIO_PIS_PASEP_UN UNIQUE(PIS_PASEP),
    CONSTRAINT TB_FUNCIONARIO_ID_PESSOA_FK FOREIGN KEY(ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
    CONSTRAINT TB_FUNCIONARIO_ID_CARGO_FK FOREIGN KEY(ID_CARGO) REFERENCES TB_CARGO(ID_CARGO),
    CONSTRAINT TB_FUNCIONARIO_ID_SETOR_FK FOREIGN KEY(ID_SETOR) REFERENCES TB_SETOR(ID_SETOR)

);



